version: 1
services:
  - type: web
    name: hentaifox
    runtime: python
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    autoDeploy: true
    region: oregon  
    
